# config context path to "/" by setting an empty string
#server:
#  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:server-keystore.jks
#    key-store-password: secret
#    key-alias: secure-server
#    trust-store: classpath:server-truststore.jks
#    trust-store-password: secret
#    enabled: true
#    client-auth: need

